src/Entity/UserRequest.php
<?php

namespace App\Entity;

use App\Repository\UserRequestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRequestRepository::class)
 */
class UserRequest
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     */
    private $create_date;

    /**
     * @ORM\Column(type="string", length=12)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="requests_references")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_reference;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->create_date = new \DateTime('now');
        $this->status = "waiting";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getUserReference(): ?User
    {
        return $this->user_reference;
    }

    public function setUserReference(?User $user_reference): self
    {
        $this->user_reference = $user_reference;

        return $this;
    }
}

src/Controller/RequestController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\UserRequest;
use App\Form\RequestFormType;
use App\Services\UserRequestService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RequestController extends AbstractController
{
    /**
     * @Route("/request", name="index_request")
     */
    public function index(UserRequestService $userRequestService): Response
    {
        $usersRequests = $userRequestService->getAllUsersRequests();
        
        return $this->render('request/index.html.twig', [
            'usersRequests' => $usersRequests,
        ]);
    }

    /**
     * @Route("/new/request", name="new_request")
     */
    public function newUserRequest(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user           = $this->getUser();
        $userRequest    = new UserRequest();
        $form           = $this->createForm(RequestFormType::class, $userRequest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRequest->setUserReference($user);

            $entityManager->persist($userRequest);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('request/new_request.html.twig', [
            'requestForm' => $form->createView(),
        ]);
    }
}

templates/request/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des requêtes{% endblock %}

{% block body %}
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>

    <div class="content px-4">
        <h4> Gestion des requêtes <h4>
        <hr>
        <p><a href="{{ path('home') }}">Retour au menu</a>
        <hr>

        <br/>
        <section>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        {% if is_granted('ROLE_ADMIN') %}
                            <th class="text-center">Username</th>
                        {% endif %}
                        <th class="text-center">Titre</th>
                        <th class="text-center">Contenu</th>
                        <th class="text-center">Date de la demande</th>
                        <th class="text-center">statut</th>
                        {% if is_granted('ROLE_ADMIN') %}
                            <th class="text-center">Action</th>
                            <th class="text-center">Supprimer</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody class="align-middle">
                {% for request in usersRequests %}
                    <tr>
                        {% if is_granted('ROLE_ADMIN') %}
                            <td>{{ request.userReference.username }} </td>
                        {% endif %}
                        <td>{{ request.title }} </td>
                        <td>{{ request.content }} </td>
                        <td>{{ request.createDate|date('d-m-Y') }} </td>
                        <td>{{ request.status }} </td>
                        {% if is_granted('ROLE_ADMIN') %}
                            <td> </td>
                            <td></td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </section>
        <br>
    </div>
{% endblock %}

templates/request/new_request.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle demande{% endblock %}

{% block body %}
    <h1>Création d'une demande</h1>

    {{ form_start(requestForm) }}
        {{ form_row(requestForm.title, {
            label: 'Titre: '
        }) }}
        {{ form_row(requestForm.content, {
            label: 'Contenu de la demande: '
        }) }}

        <button type="submit" class="btn">Envoyer</button>
    {{ form_end(requestForm) }}

    <br/><br/>
    <a href="{{ path('home') }}">Retour à la page d'accueil</a>
{% endblock %}